import { n45 } from '::root/components/editor/helpers/execK/__tests__/__data__/samples/45';
import { n68 } from '::root/components/editor/helpers/execK/__tests__/__data__/samples/68';
import { n71 } from '::root/components/editor/helpers/execK/__tests__/__data__/samples/71';
import { n55 } from '::root/components/editor/helpers/execK/__tests__/__data__/samples/55';
import { n56 } from '::root/components/editor/helpers/execK/__tests__/__data__/samples/56';
import { n49 } from '::root/components/editor/helpers/execK/__tests__/__data__/samples/49';
import { n48 } from '::root/components/editor/helpers/execK/__tests__/__data__/samples/48';
import { n46 } from '::root/components/editor/helpers/execK/__tests__/__data__/samples/46';
const testSamples = [n45, n46, n48, n49, n55, n56, n68, n71];
export { testSamples };
export type TTestSample = typeof testSamples[0];
