version: '3'
services:
  cherryjuice-staging:
    restart: always
    image: ghcr.io/ycnmhd/cherryjuice/app-staging:latest
    ports:
      - 1240:1240/tcp
    network_mode: 'host'
    env_file:
      - .env
    volumes:
      - ./nginx/shared:/etc/nginx/shared:ro
