import { Field, ID, ObjectType, registerEnumType } from '@nestjs/graphql';

export enum DOCUMENT_SUBSCRIPTIONS {
  IMPORT_PENDING = 'IMPORT_PENDING',
  IMPORT_PREPARING = 'IMPORT_PREPARING',
  IMPORT_STARTED = 'IMPORT_STARTED',
  IMPORT_FINISHED = 'IMPORT_FINISHED',
  IMPORT_FAILED = 'IMPORT_FAILED',
  IMPORT_DUPLICATE = 'IMPORT_DUPLICATE',
  DELETED = 'DELETED',

  EXPORT_PENDING = 'EXPORT_PENDING',
  EXPORT_PREPARING = 'EXPORT_PREPARING',
  EXPORT_NODES_STARTED = 'EXPORT_NODES_STARTED',
  EXPORT_IMAGES_STARTED = 'EXPORT_IMAGES_STARTED',
  EXPORT_FINISHED = 'EXPORT_FINISHED',
  EXPORT_FAILED = 'EXPORT_FAILED',
}
registerEnumType(DOCUMENT_SUBSCRIPTIONS, {
  name: 'DOCUMENT_SUBSCRIPTIONS',
});

@ObjectType()
export class DocumentSubscription {
  userId: string;

  @Field(() => DOCUMENT_SUBSCRIPTIONS)
  status: DOCUMENT_SUBSCRIPTIONS;

  @Field(() => ID)
  id: string;

  @Field(() => ID)
  name: string;

  @Field(() => ID)
  hash: string;
}
