version: '3'
services:
  cherryjuice-master:
    restart: always
    image: ghcr.io/ycnmhd/cherryjuice/app-master:latest
    ports:
      - 1250:1250/tcp
    network_mode: 'host'
    env_file:
      - .env