name: release

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install rush
        run: node common/scripts/install-run-rush.js install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node common/scripts/install-run-rush.js semantic-release
