name: cypress-tests

on: workflow_dispatch

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: NOYARNPOSTINSTALL=1 yarn install

      - name: build local dependencies
        run: yarn build:lib0:1 && yarn build:lib:1 && yarn build:lib:3 && yarn build:lib:4

      - name: cypress run with env
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./apps/client
          config-file: cypress.ci.json
          browser: chrome
          headless: true
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
